// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var cards = Cards.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Cards
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("Id")]
        public long Id { get; set; }

        [JsonProperty("GuardianStarA")]
        public long GuardianStarA { get; set; }

        [JsonProperty("GuardianStarB")]
        public long GuardianStarB { get; set; }

        [JsonProperty("Level")]
        public long Level { get; set; }

        [JsonProperty("Type")]
        public long Type { get; set; }

        [JsonProperty("Attack")]
        public long Attack { get; set; }

        [JsonProperty("Defense")]
        public long Defense { get; set; }

        [JsonProperty("Stars")]
        public long Stars { get; set; }

        [JsonProperty("CardCode")]
        public string CardCode { get; set; }

        [JsonProperty("Fusions")]
        public Fusion[] Fusions { get; set; }

        [JsonProperty("Ritual")]
        public Ritual[] Ritual { get; set; }

        [JsonProperty("Attribute")]
        public long Attribute { get; set; }
    }

    public partial class Fusion
    {
        [JsonProperty("_card1")]
        public long Card1 { get; set; }

        [JsonProperty("_card2")]
        public long Card2 { get; set; }

        [JsonProperty("_result")]
        public long Result { get; set; }
    }

    public partial class Ritual
    {
        [JsonProperty("RitualCard")]
        public long RitualCard { get; set; }

        [JsonProperty("Card1")]
        public long Card1 { get; set; }

        [JsonProperty("Card2")]
        public long Card2 { get; set; }

        [JsonProperty("Card3")]
        public long Card3 { get; set; }

        [JsonProperty("Result")]
        public long Result { get; set; }
    }

    public partial class Cards
    {
        public static Cards[] FromJson(string json) => JsonConvert.DeserializeObject<Cards[]>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Cards[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}